/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Gaussian */

#ifndef _Included_Gaussian
#define _Included_Gaussian
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Gaussian
 * Method:    runTest
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_Gaussian_runTest
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
